sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abhijitsinghas/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhijitsinghas/react-test npm test

after_success:
  - docker build -t abhijitsinghas/multi-client ./client
  - docker build -t abhijitsinghas/multi-nginx ./nginx
  - docker build -t abhijitsinghas/multi-server ./server
  - docker build -t abhijitsinghas/multi-worker ./worker
# LOGIN to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push images to docker hub
  - docker push abhijitsinghas/multi-client
  - docker push abhijitsinghas/multi-nginx
  - docker push abhijitsinghas/multi-server
  - docker push abhijitsinghas/multi-worker

# depllyments script for AWS ElasticBeanStack
# deploy:
#   provider: elasticbeanstack
#   region: "us-west-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket: "bucket-name"
#   bucket_path: "multi-docker"
#   on: 
#     branch: master
#   # AWS_ACCESS_KEY environment variable with aws access key set in Travis Console
#   access_key_id: $AWS_ACCESS_KEY     
#   # AWS_SECRET_KEY environment variable with aws secret key set in Travis Console
#   secret_access_key: $AWS_SECRET_KEY